name: mac
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ 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 }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: source script-mac.sh
    - name: JOJOBIZART
      uses: mxschmitt/action-tmate@v2
